[tool.cibuildwheel]
build-verbosity = "0"
[build-system]
requires = [
    "numpy",
    "scipy",
    "setuptools>=42",
    "wheel",
    "cmake>=3.16",
    "packaging",
    "typing_extensions",
]

build-backend = "setuptools.build_meta"

